[workspace]
members = ["time-macros"]
resolver = "2"

[package]
name = "time"
version = "0.3.15"
authors = ["Jacob Pratt <open-source@jhpratt.dev>", "Time contributors"]
edition = "2021"
rust-version = "1.60.0"
repository = "https://github.com/time-rs/time"
homepage = "https://time-rs.github.io"
keywords = ["date", "time", "calendar", "duration"]
categories = ["date-and-time", "no-std", "parser-implementations", "value-formatting"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Date and time library. Fully interoperable with the standard library. Mostly compatible with #![no_std]."
include = ["src/**/*", "LICENSE-*", "README.md", "!src/tests.rs"]

[lib]
bench = false

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "__time_03_docs"]

[features]
default = ["std"]
alloc = ["serde?/alloc"]
formatting = ["dep:itoa", "std", "time-macros?/formatting"]
large-dates = ["time-macros?/large-dates"]
local-offset = ["std"]
macros = ["dep:time-macros"]
parsing = ["time-macros?/parsing"]
quickcheck = ["dep:quickcheck", "alloc"]
rand = ["dep:rand"]
serde = ["dep:serde", "time-macros?/serde"]
serde-human-readable = ["serde", "formatting", "parsing"]
# Deprecated in favor of `serde-human-readable`.
serde-well-known = ["serde-human-readable"]
std = ["alloc"]
wasm-bindgen = ["dep:js-sys"]

# If adding an optional dependency, be sure to use the `dep:` prefix above to avoid an implicit
# feature gate.
[dependencies]
itoa = { version = "1.0.1", optional = true }
quickcheck = { version = "1.0.3", default-features = false, optional = true }
rand = { version = "0.8.4", optional = true, default-features = false }
serde = { version = "1.0.126", optional = true, default-features = false }
time-macros = { version = "=0.2.4", path = "time-macros", optional = true }

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.98"
num_threads = "0.1.2"

[target.'cfg(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi"))))'.dependencies]
js-sys = { version = "0.3.58", optional = true }

[dev-dependencies]
rand = { version = "0.8.4", default-features = false }
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
serde_json = "1.0.68"
serde_test = "1.0.126"
quickcheck_macros = "1.0.0"

[target.'cfg(__ui_tests)'.dev-dependencies]
trybuild = "1.0.63"

[target.'cfg(bench)'.dev-dependencies]
criterion = { version = "0.4.0", default-features = false }

# Significant contributions to the benchmarks provided by Emil Lundberg.
[[bench]]
name = "benchmarks"
harness = false
path = "benchmarks/main.rs"

[profile.dev]
debug = 0

[profile.test]
debug = 2
